default: &default
  adapter: postgresql
  encoding: unicode
  username: luis
  password: luis123
  host: localhost

development:
  <<: *default
  database: earnings_estimator_development

test:
  <<: *default
  database: earnings_estimator_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  
  
